"""Phase 3 training data: independent paraphrases, Siamese pairs and a leakage audit.

The validation and test queries were generated by `scripts/prepare_datasets.py`.
Nothing here imports or copies that generator. Word substitutions come from
pretrained nearest neighbours and the sentence frames are new. The build script
passes in every substitution and sentence opening the test generator uses, so
no training row reproduces them, and rows that closely match any evaluation
query are removed and counted.
"""

from __future__ import annotations

from typing import Any, Iterable

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

from src.evaluation import rank_queries
from src.preprocessing import preprocess_text
from src.tfidf_retrieval import build_tfidf_index
from src.word2vec_training import BASIC_OPTIONS


SEED = 42
PARAPHRASES_PER_FAQ = 3
DEV_VARIANT = 2  # One paraphrase per FAQ is held out for checkpoint selection.
NEIGHBOUR_CANDIDATES = 50_000
NEIGHBOUR_FLOOR = 0.55
NEIGHBOURS_KEPT = 5
# 0.5 left e-commerce paraphrases keeping 0.810 of their source tokens, above
# COVERAGE_LIMIT; 0.75 was the smallest tried rate below it on both corpora.
# The choice used FAQ questions and generated paraphrases only.
SUBSTITUTION_RATE = 0.75
DROPOUT_RATE = 0.15
MAX_ATTEMPTS = 25
HARD_NEGATIVE_POOL = 10
# The TF-IDF question similarity at which dataset preparation flagged duplicates.
DUPLICATE_SIMILARITY = 0.88
JACCARD_LIMIT = 0.8
COVERAGE_LIMIT = 0.8
LENGTH_PERCENTILE = 99

# Conversational frames written for this phase; none opens like a test template.
FRAMES = (
    "{0}?", "Could you tell me {0}?", "Quick question: {0}?", "Hi, {0}?",
    "{0}? Thanks.", "Help needed: {0}?", "{0}? Any idea?",
)
FUNCTION_WORDS = frozenset("""
a about after all also am an and any are as at be been before but by can could did do does
for from had has have here how i if in into is it its me my no nor not of on or our should
so some than that the their them then there these they this those to up us was we were what
when where which who whom why will with would you your
""".split())
NEGATIONS = frozenset({"no", "nor", "not"})


def tokens(text: object) -> list[str]:
    return preprocess_text(str(text), **BASIC_OPTIONS).split()


def normalized(text: object) -> str:
    return " ".join(tokens(text))


def template_openings(templates: Iterable[str]) -> list[str]:
    """Normalized fixed words before the first placeholder of each template."""

    return sorted({normalized(template.split("{0}")[0]) for template in templates} - {""})


def is_content_word(token: str) -> bool:
    return token.isalpha() and len(token) >= 3 and token not in FUNCTION_WORDS


def protected_tokens(question: str) -> set[str]:
    """Capitalised words inside a question, such as programme or brand names.

    Replacing "Psychology" or "Flipkart" with a neighbour would change which
    FAQ the question is about, so those words are never substituted.
    """

    protected: set[str] = set()
    for position, word in enumerate(str(question).split()):
        stripped = word.strip("\"'()[],.?!:;")
        if not stripped:
            continue
        if ((position > 0 and stripped[0].isupper())
                or (len(stripped) > 1 and stripped.isupper())
                or any(character.isdigit() for character in stripped)):
            protected.update(tokens(stripped))
    return protected


def _shares_stem(word: str, candidate: str) -> bool:
    """Inflections such as refund/refunds are not rewordings."""

    size = min(4, len(word), len(candidate))
    return word[:size] == candidate[:size]


def nearest_neighbours(
    words: Iterable[str], keyed_vectors, banned_pairs: Iterable[tuple[str, str]] = (),
    *, candidates: int = NEIGHBOUR_CANDIDATES, floor: float = NEIGHBOUR_FLOOR,
    kept: int = NEIGHBOURS_KEPT, chunk: int = 256,
) -> dict[str, list[str]]:
    """Up to `kept` substitutes per word, drawn from the most frequent pretrained words."""

    banned = set(banned_pairs)
    keys = [key for key in keyed_vectors.index_to_key[:candidates] if key.isalpha() and len(key) >= 3]
    matrix = np.asarray(
        keyed_vectors.vectors[[keyed_vectors.key_to_index[key] for key in keys]], dtype=np.float32
    )
    matrix /= np.maximum(np.linalg.norm(matrix, axis=1, keepdims=True), 1e-12)
    queries = sorted({word for word in words if word in keyed_vectors.key_to_index})

    neighbours: dict[str, list[str]] = {}
    for start in range(0, len(queries), chunk):
        batch = queries[start : start + chunk]
        vectors = np.asarray(
            keyed_vectors.vectors[[keyed_vectors.key_to_index[word] for word in batch]], dtype=np.float32
        )
        vectors /= np.maximum(np.linalg.norm(vectors, axis=1, keepdims=True), 1e-12)
        similarities = vectors @ matrix.T
        pool = min(40, similarities.shape[1])
        tops = np.argpartition(-similarities, pool - 1, axis=1)[:, :pool]
        for word, top, row in zip(batch, tops, similarities):
            ranked = sorted(top.tolist(), key=lambda position: (-float(row[position]), keys[position]))
            options = [
                keys[position] for position in ranked
                if row[position] >= floor and keys[position] != word
                and not _shares_stem(word, keys[position])
                and (word, keys[position]) not in banned
            ]
            if options:
                neighbours[word] = options[:kept]
    return neighbours


def _reword(
    source: list[str], protected: set[str], neighbours: dict[str, list[str]], rng: np.random.Generator,
) -> tuple[str, list[tuple[str, str]]]:
    """Substitute about half the content words, drop a few function words, add a frame."""

    # The first word sets the question's form ("describe", "how"); only the
    # sentence frames change it, so it is never substituted or dropped.
    replaceable = [
        position for position, token in enumerate(source)
        if position > 0 and is_content_word(token) and token not in protected and token in neighbours
    ]
    count = int(np.ceil(len(replaceable) * SUBSTITUTION_RATE))
    chosen = set(rng.choice(replaceable, size=count, replace=False).tolist()) if count else set()

    substituted: list[str] = []
    substitutions: list[tuple[str, str]] = []
    droppable: list[bool] = []
    for position, token in enumerate(source):
        if position in chosen:
            options = neighbours[token]
            replacement = options[int(rng.integers(len(options)))]
            substituted.append(replacement)
            substitutions.append((token, replacement))
            droppable.append(False)
        else:
            substituted.append(token)
            droppable.append(position > 0 and token in FUNCTION_WORDS and token not in NEGATIONS)
    words = [
        word for word, can_drop in zip(substituted, droppable)
        if not (can_drop and rng.random() < DROPOUT_RATE)
    ]
    if len(words) < min(2, len(substituted)):
        words = substituted
    frame = FRAMES[int(rng.integers(len(FRAMES)))]
    return frame.format(" ".join(words)), substitutions


def introduces_opening(words: list[str], source: list[str], openings: list[list[str]]) -> bool:
    """True when a rewording starts like an opening its source question does not."""

    return any(words[: len(opening)] == opening and source[: len(opening)] != opening
               for opening in openings)


def generate_paraphrases(
    faq_data: pd.DataFrame, neighbours: dict[str, list[str]], *, seed: int = SEED,
    avoid_openings: Iterable[str] = (),
) -> pd.DataFrame:
    """Three reworded questions per FAQ: two for training and one for the dev split.

    `avoid_openings` lists sentence openings a rewording must not introduce.
    The build script passes the evaluation templates' openings, exactly as it
    passes banned substitutions, so this module never reads their source.
    """

    opening_tokens = [opening.split() for opening in avoid_openings if opening]
    rows = []
    for faq_id, question in zip(faq_data["id"], faq_data["question"]):
        source = tokens(question)
        protected = protected_tokens(question)
        seen = {" ".join(source)}
        for variant in range(PARAPHRASES_PER_FAQ):
            rng = np.random.default_rng([seed, int(faq_id), variant])
            for _attempt in range(MAX_ATTEMPTS):
                text, substitutions = _reword(source, protected, neighbours, rng)
                key = normalized(text)
                if key and key not in seen and not introduces_opening(key.split(), source, opening_tokens):
                    break
            else:
                raise ValueError(f"Could not reword FAQ {faq_id} into distinct paraphrases")
            seen.add(key)
            rows.append({
                "query": text,
                "expected_faq_id": int(faq_id),
                "split": "dev" if variant == DEV_VARIANT else "train",
                "substitutions": " ".join(f"{original}>{new}" for original, new in substitutions),
            })
    return pd.DataFrame(rows, columns=["query", "expected_faq_id", "split", "substitutions"])


def _coverage(source: list[str], words: list[str]) -> float:
    """Share of a source question's distinct tokens that a rewording keeps."""

    return len(set(source) & set(words)) / len(set(source)) if source else 0.0


def audit_training_data(
    faq_data: pd.DataFrame, paraphrases: pd.DataFrame, evaluation: dict[str, pd.DataFrame],
    openings: Iterable[str], banned_pairs: Iterable[tuple[str, str]],
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Remove rows that reproduce an evaluation query, then check the blocking rules.

    Removal is recorded, never silent. The rows that remain must introduce no
    test-template opening and no banned substitution, and must keep at most
    COVERAGE_LIMIT of their source question's tokens on average.
    """

    banned = set(banned_pairs)
    source_tokens = {
        int(faq_id): tokens(question) for faq_id, question in zip(faq_data["id"], faq_data["question"])
    }
    evaluation_texts = [normalized(query) for frame in evaluation.values() for query in frame["query"]]
    exact = set(evaluation_texts)
    evaluation_sets = [set(text.split()) for text in evaluation_texts if text]

    keep, overlaps = [], []
    removed_exact = removed_overlap = 0
    for query in paraphrases["query"]:
        text = normalized(query)
        words = set(text.split())
        overlap = max(
            (len(words & other) / len(words | other) for other in evaluation_sets), default=0.0
        )
        overlaps.append(overlap)
        if text in exact:
            removed_exact += 1
            keep.append(False)
        elif overlap >= JACCARD_LIMIT:
            removed_overlap += 1
            keep.append(False)
        else:
            keep.append(True)
    kept = paraphrases.loc[keep].reset_index(drop=True)
    kept_overlaps = [value for value, flag in zip(overlaps, keep) if flag]

    opening_tokens = [opening.split() for opening in openings if opening]
    introduced = used_banned = 0
    coverage = []
    for row in kept.itertuples(index=False):
        words = tokens(row.query)
        source = source_tokens[int(row.expected_faq_id)]
        if introduces_opening(words, source, opening_tokens):
            introduced += 1
        coverage.append(_coverage(source, words))
        substitutions = row.substitutions if isinstance(row.substitutions, str) else ""
        for pair in substitutions.split():
            original, replacement = pair.split(">", 1)
            used_banned += (original, replacement) in banned

    reference = {}
    for name, frame in evaluation.items():
        answerable = frame[frame["is_answerable"].astype(bool)]
        values = [
            _coverage(source_tokens[int(faq_id)], tokens(query))
            for query, faq_id in zip(answerable["query"], answerable["expected_faq_id"])
        ]
        reference[name] = round(float(np.mean(values)), 4) if values else None

    mean_coverage = float(np.mean(coverage)) if coverage else 0.0
    report = {
        "generated": {split: int((paraphrases["split"] == split).sum()) for split in ["train", "dev"]},
        "removed_exact_evaluation_match": removed_exact,
        "removed_high_overlap": removed_overlap,
        "jaccard_limit": JACCARD_LIMIT,
        "kept": {split: int((kept["split"] == split).sum()) for split in ["train", "dev"]},
        "max_jaccard_with_any_evaluation_query": round(max(kept_overlaps, default=0.0), 4),
        "introduced_template_openings": introduced,
        "banned_substitutions_used": used_banned,
        "mean_source_token_coverage": round(mean_coverage, 4),
        "coverage_limit": COVERAGE_LIMIT,
        "evaluation_source_token_coverage": reference,
    }
    report["passed"] = bool(
        introduced == 0 and used_banned == 0 and mean_coverage <= COVERAGE_LIMIT
        and report["kept"]["train"] > 0 and report["kept"]["dev"] > 0
    )
    return kept, report


def build_pairs(faq_data: pd.DataFrame, paraphrases: pd.DataFrame, *, seed: int = SEED) -> pd.DataFrame:
    """One positive, one random negative and one TF-IDF hard negative per paraphrase.

    A hard negative is the highest-ranked wrong FAQ under the Phase 1 TF-IDF
    baseline. Near-duplicate questions of the gold FAQ are never negatives.
    """

    vectorizer, matrix = build_tfidf_index(faq_data, BASIC_OPTIONS)
    # Each FAQ is its own duplicate, so the gold FAQ is always excluded too.
    duplicates = cosine_similarity(matrix) >= DUPLICATE_SIMILARITY
    faq_ids = faq_data["id"].to_numpy()
    questions = faq_data["question"].tolist()
    position = {int(faq_id): index for index, faq_id in enumerate(faq_ids)}
    ranking = rank_queries(
        paraphrases["query"], faq_data, vectorizer, matrix, BASIC_OPTIONS, HARD_NEGATIVE_POOL
    )

    rows = []
    for row_number, row in enumerate(paraphrases.itertuples(index=False)):
        gold = position[int(row.expected_faq_id)]
        excluded = duplicates[gold]
        hard = None
        if ranking["has_features"][row_number]:
            hard = next(
                (position[int(faq_id)] for faq_id in ranking["ranked_ids"][row_number]
                 if not excluded[position[int(faq_id)]]),
                None,
            )
        allowed = np.flatnonzero(~excluded)
        rng = np.random.default_rng([seed, int(row.expected_faq_id), row_number])
        random_choice = int(rng.choice(allowed[allowed != hard] if hard is not None else allowed))
        hard_type = "hard"
        if hard is None:
            hard_type = "random_fallback"
            hard = int(rng.choice(allowed[allowed != random_choice]))

        base = {"text_a": row.query, "faq_id": int(row.expected_faq_id), "split": row.split}
        rows += [
            {**base, "text_b": questions[gold], "label": 1, "candidate_faq_id": int(faq_ids[gold]), "pair_type": "positive"},
            {**base, "text_b": questions[random_choice], "label": 0, "candidate_faq_id": int(faq_ids[random_choice]), "pair_type": "random"},
            {**base, "text_b": questions[hard], "label": 0, "candidate_faq_id": int(faq_ids[hard]), "pair_type": hard_type},
        ]
    columns = ["text_a", "text_b", "label", "faq_id", "candidate_faq_id", "split", "pair_type"]
    return pd.DataFrame(rows, columns=columns)


def choose_max_len(texts: Iterable[str]) -> int:
    """Cover the LENGTH_PERCENTILE of question lengths rather than guessing."""

    lengths = [len(tokens(text)) for text in texts]
    return max(1, int(np.ceil(np.percentile(lengths, LENGTH_PERCENTILE))))
